### ISSUE TITLE
[Bug] - Unabled to authenticate due to fatal error

### ISSUE THREAD

**Issue by sidedwards** [PayFabric/WooCommerce-Plugin#1]
## 🐛 Bug description
I'm getting fatal PHP errors that are preventing me from authenticating a new device. I'm not sure why, but it's not recognizing some of the `KLogger` class methods like `logNotice` and `logCrit`, yet `logInfo` seems to work fine.

```
Fatal error: Uncaught Error: Call to undefined method KLogger::logNotice() in admin/lib/payfabric/ServiceBase.php on line 19
```

## 👣 Reproduction steps
1. Try to authenticate a new device.
2. See fatal PHP errors.

## 📚 Resources
<img width="702" alt="image" src="https://user-images.githubusercontent.com/11489608/146841827-f509497f-5eb4-40d7-be48-36370af5e472.png">

**Comment by JackZhang-nodus** [comment]
@sidedwards The error thrown is that the method logNotice is undefined. In fact, the methods logNotice, logCrit and logInfo are all defined in the class [KLogger](https://github.com/PayFabric/WooCommerce-Plugin/blob/master/admin/lib/payfabric/KLogger.php). Did you override the KLogger or use any framework? You can try to add the following debug code in admin/lib/payfabric/ServiceBase.php on line 19 and check whether the logNotice method exists in the output.
`var_dump(get_class_methods(payFabric_RequestBase::$logger));`

![image](https://user-images.githubusercontent.com/86044816/147056863-bf648c12-a1b3-41e2-b7c2-491b13f306b8.png)

**Comment by sidedwards** [comment]
@JackZhang-nodus, I agree, it's strange, but I was getting this error with a fresh install of the plugin; no modifications were made. The server's PHP version is `7.4.18`.

**Comment by sidedwards** [comment]
I'm still experiencing this issue whenever attempting to save credentials on a new plugin install. I have to manually comment out the lines below in order for the credentials to save.

https://github.com/PayFabric/WooCommerce-Plugin/blob/daae8cb2b7e9f99a1ee6b5a51351b6f3a2e5708c/admin/lib/payfabric/ServiceBase.php#L18-L22

Otherwise, I get the below error due to the issue described above.

<img width="325" alt="image" src="https://user-images.githubusercontent.com/11489608/149676529-133803d4-fed7-4019-a5ea-0df0d600ab54.png">

**Comment by JackZhang-nodus** [comment]
@sidedwards 

First, Have you solved the previous error "Call to undefined method KLogger::logNotice()" by debugging?

Second, About the error "[PayFabric Class error] Invalid credentials." Can you please check whether your server has restricted the write permission of the plugin under your< WordPress root directory>\wp-content\plugins\WooCommerce-Plugin\admin\logs?

Last, I tried to install the plugin and save credentials under PHP version 7.4.18, it also works as usual.

**Comment by sidedwards** [comment]
@JackZhang-nodus, thanks for the information. After downloading the latest version of the plugin with the [updated sandbox environment details](https://github.com/PayFabric/WooCommerce-Plugin/commit/daae8cb2b7e9f99a1ee6b5a51351b6f3a2e5708c#diff-1eca853362a664258bb9e6c68bc7c3a82d5b92ac4b6bd9ff63006b1dda93047b), manually creating the `admin/logs` directory, and changing the directory ownership to `www-data`, the issue seems to be resolved.
