### ISSUE TITLE
[Feature] - "Direct" Payment Gateway

### ISSUE THREAD

**Issue by sidedwards** [PayFabric/WooCommerce-Plugin#2]
### 📜 Context

I have a customer switching from Authorize.net to Payfabric. The Authorize.net plugin supports the "Direct" payment gateway type, which allows for a better user experience at checkout.

The Payfabric plugin currently supports "Form-based" and "iFrame" payment gateway types; it would be great if it also supported "Direct" so customers can add payment details directly on the checkout page without having to click through to "Order Pay" to place the order. It would also give stores the ability to stylize the payment form.

> **Payment gateways come in several varieties:**
>
> 1. Form based – This is where the user must click a button on a form that then redirects them to the payment processor on the gateway’s own website. Example: PayPal standard, Authorize.net DPM
> 2. iFrame based – This is when the gateway payment system is loaded inside an iframe on your store. Example: SagePay Form, PayPal Advanced
> 3. Direct – This is when the payment fields are shown directly on the checkout page and the payment is made when ‘place order’ is pressed. Example: PayPal Pro, Authorize.net AIM
> 4. Offline – No online payment is made. Example: Cheque, Bank Transfer

### 🔗 References

- https://woocommerce.com/document/payment-gateway-api/#section-1
- https://woocommerce.com/document/payment-gateway-api/#section-6

**Comment by JackZhang-nodus** [comment]
Thank you for your suggestion. Our product team is considering supporting "Direct" payment gateway in the next version, and it will be weighed up and prioritized along with other requests within the development timeline.

**Comment by sidedwards** [comment]
@JackZhang-nodus any update on a timeline for this feature?

**Comment by JackZhang-nodus** [comment]
It's included in our latest release v2.0.0. Thank you for your contribution!
