### ISSUE TITLE
[Feature] - Custom Order Success Redirects

### ISSUE THREAD

**Issue by sidedwards** [PayFabric/WooCommerce-Plugin#3]
### 📜 Context
Currently, after an order is placed, the plugin redirects users back to the shop page. It would be ideal if the plugin used the native WooCommerce [`order-received` endpoint](https://woocommerce.com/document/woocommerce-endpoints-2-1/#section-1) or allowed custom redirect endpoints.

### 🔗 References

https://github.com/PayFabric/WooCommerce-Plugin/blob/daae8cb2b7e9f99a1ee6b5a51351b6f3a2e5708c/admin/class-payfabric-gateway-request.php#L270-L273

**Comment by semantic-support** [comment]
- [ ] @sidedwards to send a follow-up to Tingyi if nothing comes through by 2/15/22

**Comment by JackZhang-nodus** [comment]
Yes, it would be better, your suggestion has been submitted to the project team and will be prioritized along with other requests within the development timeline.

**Comment by sidedwards** [comment]
This seems to be resolved with [`v1.1.0`](https://github.com/PayFabric/WooCommerce-Plugin/releases/tag/v1.1.0).
