### ISSUE TITLE
Wordpress Error When Saving Device Id & Password

### ISSUE THREAD

**Issue by gavinsauder** [PayFabric/WooCommerce-Plugin#4]
When setting up payfabric in woocommerce you can't setup the merchant data for PayFabric system. When adding your device ID and password and clicking save you get this error: 
![image](https://user-images.githubusercontent.com/40070195/179997841-11fce72a-5481-42af-9680-b4a3d55013e3.png)

Wordpress logs show this:
` PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/lib/payfabric/Request.php:9
Stack trace:
#0 /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/lib/payfabric/RequestBase.php(185): payFabric_Request->sendXml()
#1 /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/lib/payments.php(93): payFabric_RequestBase->processRequest()
#2 /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/class-payfabric-gateway-request.php(452): payments->creditCardSale()
#3 /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/class-payfabric-gateway.php(414): PayFabric_Gateway_Request->do_check_gateway()
#4 /var/www/html/wp-includes/class-wp-hook.php(307): PayFabric->process_admin_options()
#5 /var/www/html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#6 /var/www/html/wp-includes/plugin.php(476): WP_Hook->do_action()
#7 /var/www/html/wp-content/plugins/woocommerce/includes/admin/settings/class-w in /var/www/html/wp-content/plugins/WooCommerce-Plugin-master/admin/lib/payfabric/Request.php on line 9`

Currently running:
Ubuntu 20.04.3
Apache 2.4.41
PHP 7.4.3
Wordpress 6.0.1
WooCommerce 6.7.0
WooCommerce PayFabric Gateway 1.1.0

**Comment by JackZhang-nodus** [comment]
This error occurs when cURL library is not installed on your system or enabled in your PHP installation, please install the cURL extension and enable it in your php.ini.

**Comment by gavinsauder** [comment]
Ah ok. Yes, that was solved with adding cURL. Although, now when entering device id and password I get this message: `Unable to create new transaction. The gateway account cannot be blank.`  I don't see that you can assign the gateway accounts. Any advice?

**Comment by JackZhang-nodus** [comment]
Please go to PayFabric portal to configure the default gateway by clicking Settings > Gateway Account Configuration, click '+ New Gateway Account' if the payment gateway account is not associated to an existing PayFabric account, and then set the default gateway under Default Gateway Settings. Please refer to user guide in [PayFabric
](https://github.com/PayFabric/Portal/blob/master/PayFabric/README.md)
Still having questions? Please contact support@payfabric.com.
